### ISSUE TITLE
Rankings table is misaligned 

### ISSUE THREAD

**Issue by cwang395** [jiangdaniel/pie-match-sched#15]

**Comment by viviehn** [comment]
Closed with https://github.com/jiangdaniel/pie-match-sched/commit/bb172f5f4cdee9329640a03c41a9b334f22c5467, but please check to make sure I didn't break anything

**Comment by cwang395** [comment]
The ranking page looks great! The fab still doesn't refresh the page :/ but we'll keep working on that
