### ISSUE TITLE
Browsing finalcomp.pierobotics.org on phone mirrors browsing on phone

### ISSUE THREAD

**Issue by cwang395** [jiangdaniel/pie-match-sched#18]
If I visit http://finalcomp.pierobotics.org on my phone and on my laptop at the same time, then navigating through the website on my laptop will be mirrored by my phone's browser.

To see the code that has been pushed to PiE's DO server, visit the [production](https://github.com/jiangdaniel/pie-match-sched/tree/production) branch.

**Comment by cwang395** [comment]
Can't replicate (yet) using Safari for Mac 9.1, OS X 10.11.4, iOS 9.3.1

**Comment by dwai213** [comment]
Replicated with OSX 11.4 on Chrome with iOS 9.3.1
I would browse the site on phone and my browser would mirror that.

I browsed with incognito window on computer and I observed the same effect

**Comment by wli** [comment]
Remove this script and it'll fix it: http://finalcomp.pierobotics.org/browser-sync/browser-sync-client.2.12.3.js

**Comment by wli** [comment]
Looks like the proper way to do this is to run `gulp build-deploy-gh-pages`, which will minify everything (making it load 10x faster) and remove the browsersync script.

**Comment by wli** [comment]
You can see that in the [source](view-source:http://finalcomp.pierobotics.org/) of the page, you've missed a gulp preprocessing step:

```
  <!-- build:remove -->
  <script id="__bs_script__">//<![CDATA[
    document.write("<script async src='/browser-sync/browser-sync-client.2.12.3.js'><\/script>".replace("HOST", location.hostname));
//]]></script>

  <!-- endbuild -->
```

**Comment by jiangdaniel** [comment]
Deploying on Github pages instead, where the issue is not present
